apiVersion: v1
name: recyclebin-chart
description: A Helm chart for the ACK service controller for Amazon EBS Recycle Bin (Recycle Bin)
version: 0.0.2
appVersion: 0.0.2
home: https://github.com/aws-controllers-k8s/recyclebin-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/recyclebin-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Recycle Bin Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/recyclebin-maintainer
keywords:
  - aws
  - kubernetes
  - recyclebin
